import { IgdbAgeRating } from "./igdb-age-rating.interface";
import { IgdbArtwork } from "./igdb-artwork.interface";
import { IgdbCover } from "./igdb-cover.interface";
import { IgdbExternalGame } from "./igdb-external-game.interface";
import { IgdbGameCategory } from "./igdb-game-category.enum";
import { IgdbGameStatus } from "./igdb-game-status.enum";
import { IgdbGenre } from "./igdb-genre.interface";
import { IgdbInvolvedCompany } from "./igdb-involved-company.interface";
import { IgdbKeyword } from "./igdb-keyword.interace";
import { IgdbScreenshot } from "./igdb-screenshot.interface";
import { IgdbTheme } from "./igdb-theme.interface";
import { IgdbVideo } from "./igdb-video.interface";
import { IgdbWebsite } from "./igdb-website.interface";

export interface IgdbGame {
  id: number;
  age_ratings: IgdbAgeRating[];
  aggregated_rating: number;
  aggregated_rating_count: number;
  alternative_names: number[];
  artworks: IgdbArtwork[];
  bundles: number[];
  category: IgdbGameCategory;
  collection: number;
  cover: IgdbCover;
  created_at: number;
  dlcs: number[];
  external_games: IgdbExternalGame[];
  first_release_date: number;
  franchises: number[];
  game_engines: number[];
  game_modes: number[];
  genres: IgdbGenre[];
  involved_companies: IgdbInvolvedCompany[];
  keywords: IgdbKeyword[];
  multiplayer_modes: number[];
  name: string;
  platforms: number[];
  player_perspectives: number[];
  rating: number;
  rating_count: number;
  release_dates: number[];
  screenshots: IgdbScreenshot[];
  similar_games: number[];
  slug: string;
  status: IgdbGameStatus;
  storyline: string;
  summary: string;
  tags: number[];
  themes: IgdbTheme[];
  total_rating: number;
  total_rating_count: number;
  updated_at: number;
  url: string;
  videos: IgdbVideo[];
  websites: IgdbWebsite[];
  checksum: string;
  language_supports: number[];
  game_localizations: number[];
  collections: number[];
}
