services:
  gamevault-backend:
    build: .
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USERNAME: gamevault
      DB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - type: bind
        source: files
        target: /files
        is_directory: true
      - type: bind
        source: media
        target: /media
        is_directory: true
      - type: bind
        source: logs
        target: /logs
        is_directory: true
      - type: bind
        source: config
        target: /config
        is_directory: true
      - type: bind
        source: plugins
        target: /plugins
        is_directory: true
      - type: bind
        source: savefiles
        target: /savefiles
        is_directory: true

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: gamevault
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gamevault
    volumes:
      - type: bind
        source: databae
        target: /var/lib/postgresql/data
        is_directory: true
