export enum RawgPlatform {
  "PC" = 1,
  "PlayStation" = 2,
  "Xbox" = 3,
  "iOS" = 4,
  "Mac" = 5,
  "Linux" = 6,
  "Nintendo" = 7,
  "Android" = 8,
  "Atari" = 9,
  "Commodore / Amiga" = 10,
  "SEGA" = 11,
  "3DO" = 12,
  "Neo Geo" = 13,
}
