export enum GameExistence {
  DOES_NOT_EXIST = "DOES_NOT_EXIST",
  EXISTS = "EXISTS",
  EXISTS_BUT_ALTERED = "EXISTS_BUT_ALTERED",
  EXISTS_BUT_DELETED_IN_DATABASE = "EXISTS_BUT_DELETED_IN_DATABASE",
}
