export enum State {
  UNPLAYED = "UNPLAYED",
  INFINITE = "INFINITE",
  PLAYING = "PLAYING",
  COMPLETED = "COMPLETED",
  ABORTED_TEMPORARY = "ABORTED_TEMPORARY",
  ABORTED_PERMANENT = "ABORTED_PERMANENT",
}
